// Generated by CoffeeScript 1.6.3
(function() {
  var Enum, EnumError, HTTPEnum, assert, keys;

  assert = require('chai').assert;

  Enum = require('../src/enum.js').Enum;

  EnumError = require('../src/enum.js').EnumError;

  HTTPEnum = null;

  keys = {
    A: 1,
    B: "b",
    C: false
  };

  suite("Enum.js", function() {
    setup(function() {
      return HTTPEnum = Enum.extend({
        OK: 200,
        ERROR: 500
      });
    });
    suite("#prototype.constructor", function() {
      test("Should throw the EnumError", function() {
        var err, error, result;
        error = null;
        try {
          result = new HTTPEnum(123);
        } catch (_error) {
          err = _error;
          error = err;
        }
        assert.isNotNull(error);
        assert.instanceOf(error, Error);
        return assert.instanceOf(error, EnumError);
      });
      test("Should return instance of HTTPEnum", function() {
        var result;
        result = new HTTPEnum(HTTPEnum.OK);
        assert.ok(result);
        return assert.instanceOf(result, HTTPEnum);
      });
      return test("Should return instance of Enum", function() {
        var result;
        result = new HTTPEnum(HTTPEnum.OK);
        assert.ok(result);
        return assert.instanceOf(result, Enum);
      });
    });
    suite("#make", function() {
      return test("Should return correct instance of HTTPEnum", function() {
        var result, value;
        result = HTTPEnum.make("OK");
        value = HTTPEnum.OK;
        assert.ok(result);
        assert.equal(result.value(), value);
        return assert.instanceOf(result, HTTPEnum);
      });
    });
    suite("#keyOf", function() {
      test("Should return property name if it exists", function() {
        var result;
        result = HTTPEnum.keyOf(HTTPEnum.OK);
        assert.isString(result);
        return assert.isTrue(result === "OK");
      });
      return test("Should return null if property doesn't exist", function() {
        var result;
        result = HTTPEnum.keyOf(123);
        return assert.isNull(result);
      });
    });
    suite("#has", function() {
      test("Should return true if property exists", function() {
        var result;
        result = HTTPEnum.has(HTTPEnum.OK);
        assert.isBoolean(result);
        return assert.isTrue(result);
      });
      return test("Should return false if doesn't have existing value", function() {
        var result;
        result = HTTPEnum.has(123);
        assert.isBoolean(result);
        return assert.isFalse(result);
      });
    });
    suite("#values", function() {
      return test("Should return correct list of values", function() {
        var MyEnum, keysWrong, result;
        keysWrong = {
          A: 0,
          B: "c"
        };
        MyEnum = Enum.extend(keys);
        result = MyEnum.values();
        assert.isObject(result);
        assert.deepEqual(result, keys);
        return assert.notDeepEqual(result, keysWrong);
      });
    });
    return suite("#extend", function() {
      test("Should return instance of Enum", function() {
        var TestEnum, obj;
        TestEnum = Enum.extend(keys);
        obj = new TestEnum(1);
        return assert.instanceOf(obj, Enum);
      });
      test("Should return instance of TestEnum", function() {
        var TestEnum, obj;
        TestEnum = Enum.extend(keys);
        obj = new TestEnum(1);
        return assert.instanceOf(obj, TestEnum);
      });
      test("Should save deep inheritance", function() {
        var DeeperTestEnum, TestEnum, deepObj, obj;
        TestEnum = Enum.extend(keys);
        DeeperTestEnum = TestEnum.extend(keys);
        obj = new TestEnum(1);
        deepObj = new DeeperTestEnum(1);
        assert.instanceOf(deepObj, Enum);
        assert.instanceOf(deepObj, TestEnum);
        assert.instanceOf(deepObj, DeeperTestEnum);
        return assert.notInstanceOf(obj, DeeperTestEnum);
      });
      test("Should return Enum, that have all given constants", function() {
        var TestEnum;
        TestEnum = Enum.extend(keys);
        return assert.deepEqual(TestEnum.values(), keys);
      });
      test("Should return Enum, that have all given prototype methods", function() {
        var TestEnum, obj;
        TestEnum = Enum.extend(keys, {
          callMe: function() {
            return true;
          }
        });
        obj = new TestEnum(1);
        assert.isFunction(obj.callMe);
        return assert.isTrue(obj.callMe());
      });
      return test("Should return Enum, that have all given static methods", function() {
        var TestEnum;
        TestEnum = Enum.extend({
          callMe: function() {
            return true;
          }
        });
        assert.isFunction(TestEnum.callMe);
        return assert.isTrue(TestEnum.callMe());
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=enum-test.map
*/
